### ISSUE TITLE
[ANDROID] Could not find com.microblink:blinkid

### ISSUE THREAD

**Issue by matias91** [microblink/blinkid-react-native#10]
Hi.

After following the installation guide on my project i run `react-native run-android` and i get the following error:

<img width="533" alt="captura de pantalla 2017-08-08 a la s 18 49 57" src="https://user-images.githubusercontent.com/2778383/29096270-888b8e9c-7c6a-11e7-98dd-f0454f0d7ace.png">

I also tried to run the demo and i get the same error.

Sorry if this is trivial, but i'm new with Android.

thanks in advance

**Comment by DoDoENT** [comment]
Please make sure that Microblink's maven repository is present in your build.gradle, as described in [documentation](https://github.com/BlinkID/blinkid-android#using-gradle-or-android-studio).

**Comment by matias91** [comment]
Thanks for the answer, @DoDoENT! It's working fine now.
Maybe would be helpful to include that link in the installation steps of this repository, since is also necessary for React Native users.

**Comment by DoDoENT** [comment]
Hi @matias91, as far as I see, the [android wrapper already contains this line](https://github.com/BlinkID/blinkid-react-native/blob/master/src/android/build.gradle#L22), so if you have initialised the project by [following readme](https://github.com/BlinkID/blinkid-react-native#installation) or by using [demo app initialisation script](https://github.com/BlinkID/blinkid-react-native/blob/master/initReactNativeDemoApp.sh), this line should have been added to your `build.gradle`.

However, if it makes it more clear, we can add this note to the installation guide.
