### ISSUE TITLE
Make available for setting tooltipLabel property

### ISSUE THREAD

**Issue by hunght** [microblink/blinkid-react-native#11]
Please make available for setting tooltipLabel property, I knew it can do this on blinkid-ios

**Comment by ghensley** [comment]
This was added to blinkid-react-native-ios, but hasn't been added to the merged project. I ran into difficulties trying to figure out how to do it for android, since I believe it required replacing the entire overlay.

**Comment by hunght** [comment]
I only need on iOS, so could be any way to use it on iOS

**Comment by ghensley** [comment]
If you use: https://github.com/BlinkID/blinkid-react-native-ios you can set the options boxRatio and tooltipText.

I use this for USDL barcodes, since we had a lot of issues with users not understanding that they were supposed to put the barcode in the card-shaped rectangle: 

scan({
    boxRatio: 2.5,
    tooltipText: "Scan the barcode",
    isFrontCamera: false,
    addEudlRecognizer: false,
    addMrtdRecognizer: false,
    addUsdlRecognizer: true,
    shouldReturnCroppedDocument: true,
    shouldReturnSuccessfulFrame: true
  })

**Comment by hunght** [comment]
thank you, i already create a branch that fork and merge what you did to make tooltipLabel available on iOS, so no need to do here, i will off this topic.
