### ISSUE TITLE
Link module error 

### ISSUE THREAD

**Issue by jojoucsd** [microblink/blinkid-react-native#27]
After npm i --save blinkid-react-native 

linking module throw error 

rnpm-install info Android module blinkid-react-native is already linked 
rnpm-install ERR! Something went wrong while linking. Error: Expected "/*", "//", or "{" but "<" found. 
Please file an issue here: https://github.com/facebook/react-native/issues

solution I tried : 
delete node_modules and reinstall
remove Pods and reinstall Pods
errors remains , any suggestions ?

**Comment by lirfu** [comment]
Hi @jojoucsd,

the fb plugin had a similar [issue](https://github.com/facebook/react-native/issues/10032). Please examine their solution and report back on your success.

Hope this helps!

**Comment by jojoucsd** [comment]
Hi, lirfu,
thanks for the reply, got mine fixed after removed my android file and run a react-native upgrade. after the upgrade, react-native links works. Thanks for you help!
